- name: configure mysql server
  hosts: mysql
  become: yes  # remote server
  vars_files:
  - /var/expense/credentials_mysql.yaml #  ansible vault [credentials are kept inside the ansible vault]
  roles:
  - mysql

  # all the script is placed in a proper order in the roles folder 
  # that includes tasks, vars, handlers etc. and we are calling the rolre here in the play book.
  