- name: configure mysql server
  hosts: mysql
  become: yes
  vars_files:
  - /var/expense/credentials_mysql.yaml
  roles:
  - mysql

  # all the script is placed in a proper order in the roles folder
  